version: '3.8'
services:
    django:
        build:
            context: ./
        container_name: django
        command: >
          sh -c "python manage.py makemigrations &&
                python manage.py migrate &&
                python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        restart: always
        depends_on:
            - mysqldb
            - rabbitmq
            - redis
        env_file:
            - .env
        volumes:
            - './:/backend'  # 로컬 프로젝트 루트를 컨테이너 /backend에 연결
            - './media/fonts:/app/media/fonts' # 폰트 디렉토리 연결
        networks:
            - app-tier
        dns:
            - 8.8.8.8  # Google Public DNS
            - 8.8.4.4  # Google Public DNS

    mysqldb:
        image: mysql:latest
        env_file:
            - .env
        ports:
            - '3305:3306'
        volumes:
            - 'mysqldata:/var/lib/mysql'  # 로컬 볼륨 연결
        restart: always
        networks:
            - app-tier

    phpmyadmin:
        image: phpmyadmin
        restart: always
        links:
          - mysqldb
        ports:
          - 8080:80
        environment:
          PMA_ARBITRARY: 1
          PMA_HOST: mysqldb
          PMA_PORT: 3306
        networks:
          - app-tier

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"  # RabbitMQ 브로커 포트
            - "15672:15672"  # RabbitMQ 관리 UI 포트
        env_file:
            - .env
        networks:
            - app-tier
        dns:
            - 8.8.8.8
            - 8.8.4.4

    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - app-tier
        dns:
            - 8.8.8.8
            - 8.8.4.4

    celery:
        build:
            context: .
        container_name: celery
        command: celery -A config worker --loglevel=info
        depends_on:
            - rabbitmq
            - redis
        volumes:
            - .:/backend  # Django와 같은 볼륨 연결
        env_file:
            - .env
        networks:
            - app-tier
        dns:
            - 8.8.8.8
            - 8.8.4.4

volumes:
    mysqldata:

networks:
    app-tier:
        driver: bridge
