global:
  scrape_interval: 15s # 메트릭 수집 인터벌
  evaluation_interval: 15s # 메트릭 평가 인터벌

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']

rule_files:
  - "/etc/alert-rules.yml"

scrape_configs:
  - job_name: 'prometheus-data'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'cadvisor-data'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'django'
    static_configs:
      - targets: ['django:8000']
